import React from 'react'
export const ADD_CARD = 'CARD/ADD_CARD'
export const REMOVE_CARD = 'CARD/REMOVE_CARD'
export const CHANGE_CARD = 'CARD/CHANGE_CARD'
export const DONE_CARD = 'CARD/DONE'
export const LOAD_CARD = 'CARD/LOAD_CARD'